    # vi: ft=nginx
    # Copied from https://github.com/NginxProxyManager/nginx-proxy-manager/blob/bb0f4bfa626bfa30e3ad2fa31b5d759c9de98559/docker/rootfs/etc/nginx/conf.d/include/block-exploits.conf

    # Var to keep track of whether a request should be blocked.
    set $block 0;

    if ($query_string ~ "union.*select.*\(") {
      set $block 1;
    }

    if ($query_string ~ "union.*all.*select.*") {
      set $block 1;
    }

    if ($query_string ~ "concat.*\(") {
      set $block 1;
    }

    ## Block file injections
    if ($query_string ~ "[a-zA-Z0-9_]=(\.\.//?)+") {
      set $block 1;
    }

    if ($query_string ~ "[a-zA-Z0-9_]=/([a-z0-9_.]//?)+") {
      set $block 1;
    }

    ## Block common exploits
    if ($query_string ~ "(<|%3C).*script.*(>|%3E)") {
      set $block 1;
    }

    if ($query_string ~ "GLOBALS(=|\[|\%[0-9A-Z]{0,2})") {
      set $block 1;
    }

    if ($query_string ~ "_REQUEST(=|\[|\%[0-9A-Z]{0,2})") {
      set $block 1;
    }

    if ($query_string ~ "proc/self/environ") {
      set $block 1;
    }

    if ($query_string ~ "mosConfig_[a-zA-Z_]{1,21}(=|\%3D)") {
      set $block 1;
    }

    if ($query_string ~ "base64_(en|de)code\(.*\)") {
      set $block 1;
    }

    # Block common paths that lead to a 404 anyway.
    if ($request_uri ~* ({{ regex_block_paths }})) {
      set $block 1;
    }

    # Block extensions never used by our app.
    if ($request_uri ~*  \.({{ regex_block_extensions }})$ ){
      set $block 1;
    }

    # Do the block by returning a 403.
    if ($block = 1) {
      return 403;
    }

    ## Block user agents
    set $block_agent 0;

    # Disable Akeeba Remote Control 2.5 and earlier
    if ($http_user_agent ~ "Indy Library") {
      set $block_agent 1;
    }

    # Common bandwidth hoggers and hacking tools.
    if ($http_user_agent ~ "libwww-perl") {
      set $block_agent 1;
    }

    if ($http_user_agent ~ "GetRight") {
      set $block_agent 1;
    }

    if ($http_user_agent ~ "GetWeb!") {
      set $block_agent 1;
    }

    if ($http_user_agent ~ "Go!Zilla") {
      set $block_agent 1;
    }

    if ($http_user_agent ~ "Download Demon") {
      set $block_agent 1;
    }

    if ($http_user_agent ~ "Go-Ahead-Got-It") {
      set $block_agent 1;
    }

    if ($http_user_agent ~ "TurnitinBot") {
      set $block_agent 1;
    }

    if ($http_user_agent ~ "GrabNet") {
      set $block_agent 1;
    }

    if ($block_agent = 1) {
      return 403;
    }
