docker-compose-yaml: docker-compose.yml

project: drupalmountaincamp-ch

tasks:
  # pre-rollout:
  #   - run:
  #     name: drush sql-dump
  #     command: mkdir -p /app/web/sites/default/files/private/ && drush sql-dump --ordered-dump --gzip --result-file=/app/web/sites/default/files/private/pre-deploy-dump.sql.gz || true
  #     service: cli

  post-rollout:
      - run:
          name: If no Drupal installed - get database from PROD
          command: |
              if [[ ${LAGOON_GIT_SAFE_BRANCH} != "prod" ]] && ! drush status --fields=bootstrap | grep -q "Successful"; then
                drush -y sql-sync @lagoon.drupalmountaincamp-ch-prod @self
              fi
          service: cli
          shell: bash
      - run:
          name: drush updb
          command: drush -y updb --no-cache-clear
          service: cli
      - run:
          name: drush cr
          command: drush -y cr
          service: cli
      - run:
          name: drush cim
          command: drush -y cim
          service: cli
      - run:
          name: drush cr
          command: drush -y cr
          service: cli

environments:
  prod:
      cronjobs:
          - name: drush cron
            schedule: "*/15 * * * *"
            command: drush cron
            service: cli
      routes:
          - nginx:
              - "drupalmountaincamp.ch"
              - "www.drupalmountaincamp.ch"
              - "cfp.drupalmountaincamp.ch"
