ARG CLI_IMAGE
FROM ${CLI_IMAGE} as cli

FROM amazeeio/nginx-drupal
RUN echo "~^www.drupalmountaincamp.ch   http://drupalmountaincamp.ch\$request_uri;" >> /etc/nginx/redirects-map.conf

COPY --from=cli /app /app
# Define where the Drupal Root is located
ENV WEBROOT=/web
