FROM amazeeio/node:8-builder as nodebuilder

COPY .npmrc gulpfile.js package.json /app/

RUN npm install --production
RUN npm run gulp -- compile --env=prod

FROM amazeeio/php:7.0-cli-drupal

COPY composer.json composer.lock /app/
COPY scripts /app/scripts
COPY patches /app/patches

RUN composer install --prefer-dist --no-dev --no-suggest --optimize-autoloader --apcu-autoloader

COPY --from=nodebuilder /app/ /app/

COPY . /app

# Define where the Drupal Root is located
ENV WEBROOT=/web
