#ddev-generated
# If you remove the ddev-generated line above you
# are responsible for maintaining this file. DDEV will not then
# update it, for example if you add `additional_hostnames`, etc.

http:
  routers:
    starterkit-elasticsearch-9200-http:
      entrypoints:
        - http-9200
      rule: HostRegexp(`^starterkit\.ddev\.site$`)
      
      service: "starterkit-elasticsearch-9200"
      ruleSyntax: v3
      tls: false
      # middlewares:
      #   - "starterkit-redirectHttps"
    starterkit-web-80-http:
      entrypoints:
        - http-80
      rule: HostRegexp(`^starterkit\.ddev\.site$`)
      
      service: "starterkit-web-80"
      ruleSyntax: v3
      tls: false
      # middlewares:
      #   - "starterkit-redirectHttps"
    starterkit-web-8025-http:
      entrypoints:
        - http-8025
      rule: HostRegexp(`^starterkit\.ddev\.site$`)
      
      service: "starterkit-web-8025"
      ruleSyntax: v3
      tls: false
      # middlewares:
      #   - "starterkit-redirectHttps"
    starterkit-xhgui-80-http:
      entrypoints:
        - http-8143
      rule: HostRegexp(`^starterkit\.ddev\.site$`)
      
      service: "starterkit-xhgui-80"
      ruleSyntax: v3
      tls: false
      # middlewares:
      #   - "starterkit-redirectHttps"
    
    
    starterkit-elasticsearch-9200-https:
      entrypoints:
        - http-9201
      rule: HostRegexp(`^starterkit\.ddev\.site$`)
      
      service: "starterkit-elasticsearch-9200"
      ruleSyntax: v3
      
      tls: true
      
    
    
    starterkit-web-80-https:
      entrypoints:
        - http-443
      rule: HostRegexp(`^starterkit\.ddev\.site$`)
      
      service: "starterkit-web-80"
      ruleSyntax: v3
      
      tls: true
      
    starterkit-web-8025-https:
      entrypoints:
        - http-8026
      rule: HostRegexp(`^starterkit\.ddev\.site$`)
      
      service: "starterkit-web-8025"
      ruleSyntax: v3
      
      tls: true
      
    
    starterkit-xhgui-80-https:
      entrypoints:
        - http-8142
      rule: HostRegexp(`^starterkit\.ddev\.site$`)
      
      service: "starterkit-xhgui-80"
      ruleSyntax: v3
      
      tls: true
      
    

  middlewares:
    starterkit-redirectHttps:
      redirectScheme:
        scheme: https
        permanent: true

  services:
    starterkit-elasticsearch-9200:
      loadbalancer:
        servers:
          - url: http://ddev-starterkit-elasticsearch:9200
        
    
    starterkit-web-80:
      loadbalancer:
        servers:
          - url: http://ddev-starterkit-web:80
        
    starterkit-web-8025:
      loadbalancer:
        servers:
          - url: http://ddev-starterkit-web:8025
        
    
    
    starterkit-xhgui-80:
      loadbalancer:
        servers:
          - url: http://ddev-starterkit-xhgui:80
        
    
    

tls:
  certificates:
    - certFile: /mnt/ddev-global-cache/traefik/certs/starterkit.crt
      keyFile: /mnt/ddev-global-cache/traefik/certs/starterkit.key