# vim: set syntax=nginx ft=nginx

# We keep the config in a seperate file because this one gets
# compiled when building the container. By including it like this we
# can alter the config without having to rebuild the container.
include /app/lando/nginx/custom.conf;
