# Override any of the properties from base.yml for this environment.
hmr: false
certbot_enabled: false
basic_auth: false
fallback: false
error_page: /builds/bazinga/mountaincamp/frontend/public

sites:
  mountaincamp_ci:
    server_name: mountaincamp_ci
    frontend_host: localhost
    frontend_port: 3000
    storybook_port: 3010

php:
  fastcgi_pass: 'localhost:9000'
  server_name: localhost
  root: /builds/liip/nuxt-graphql-starterkit/drupal/docroot
