#!/usr/bin/env bash
# Runs the Lagoon nginx image with .lagoon/nginx-lagoon.conf against stub
# upstreams and checks the response headers nginx adds, once as a production
# and once as a development environment.
#
# Usage: scripts/ci/nginx-headers.sh [--report] [path/to/nginx.conf]
#   --report  print the headers only, without checking them
set -euo pipefail

REPORT_ONLY=false
if [[ "${1:-}" == "--report" ]]; then
  REPORT_ONLY=true
  shift
fi

ROOT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/../.." && pwd)"
CONFIG="$(realpath "${1:-$ROOT_DIR/.lagoon/nginx-lagoon.conf}")"

# The image the Dockerfile builds the nginx service from, so this check runs
# against the release that gets deployed.
NGINX_IMAGE="$(awk '$1 == "FROM" && $2 ~ /^uselagoon\/nginx-drupal:/ { print $2 }' "$ROOT_DIR/.lagoon/Dockerfile")"
if [[ -z "$NGINX_IMAGE" ]]; then
  echo "No uselagoon/nginx-drupal image found in .lagoon/Dockerfile" >&2
  exit 1
fi
PHP_IMAGE="php:8.3-fpm-alpine"
FRONTEND_IMAGE="nginx:alpine"
PUBLIC_HOST="drupalmountaincamp.ch"
AUTOGENERATED_HOST="nginx.prod.example.amazee.io"
NOINDEX="noindex, nofollow"
SVG_SANDBOX_CSP="default-src 'none'; style-src 'unsafe-inline'; sandbox; frame-ancestors 'self'"
START_TIMEOUT_SECONDS=30

RUN_ID="nginx-headers-$$"
WORK_DIR="$(mktemp -d)"
FAILURES=0

cleanup() {
  docker rm -f "$RUN_ID-nginx" "$RUN_ID-php" "$RUN_ID-frontend" >/dev/null 2>&1 || true
  docker network rm "$RUN_ID" >/dev/null 2>&1 || true
  rm -rf "$WORK_DIR"
}
trap cleanup EXIT

# A docroot with one file per kind nginx serves from disk, and a front
# controller that answers like Drupal, with a Cache-Control of its own.
mkdir -p "$WORK_DIR/docroot/core/misc" "$WORK_DIR/docroot/sites/default/files"
cat > "$WORK_DIR/docroot/index.php" <<'PHP'
<?php
// Answers like Drupal for anonymous visitors: a redirect to the login form,
// access denied, or a page, each with a Cache-Control of its own.
$path = parse_url($_SERVER['REQUEST_URI'], PHP_URL_PATH);
header('Cache-Control: no-cache, private');
if (str_ends_with($path, '/user/register')) {
  header('Location: /user/login?destination=/user/register', true, 307);
}
elseif (preg_match('#/admin(/|$)#', $path)) {
  http_response_code(403);
}
echo 'drupal ' . $path;
PHP
echo 'console.log(1)' > "$WORK_DIR/docroot/core/misc/drupal.js"
echo 'png' > "$WORK_DIR/docroot/sites/default/files/photo.png"
echo '<svg xmlns="http://www.w3.org/2000/svg"/>' > "$WORK_DIR/docroot/sites/default/files/icon.svg"
chmod -R a+rX "$WORK_DIR"

cat > "$WORK_DIR/frontend.conf" <<'CONF'
server {
  listen 3000;
  location / {
    add_header Cache-Control "public, max-age=300";
    return 200 "frontend $request_uri";
  }
}
CONF

start_stack() {
  local environment_type="$1"
  cleanup_containers
  docker network create "$RUN_ID" >/dev/null 2>&1 || true
  # The image's entrypoint rewrites the config in place, so it gets a copy.
  cp "$CONFIG" "$WORK_DIR/app.conf"
  chmod a+rw "$WORK_DIR/app.conf"
  docker run -d --name "$RUN_ID-frontend" --network "$RUN_ID" --network-alias frontend \
    -v "$WORK_DIR/frontend.conf:/etc/nginx/conf.d/default.conf:ro" "$FRONTEND_IMAGE" >/dev/null
  docker run -d --name "$RUN_ID-nginx" --network "$RUN_ID" -p 127.0.0.1::8080 \
    -e LAGOON_ENVIRONMENT_TYPE="$environment_type" \
    -e LAGOON_AUTOGENERATED_ROUTES="https://$AUTOGENERATED_HOST" \
    -v "$WORK_DIR/app.conf:/etc/nginx/conf.d/app.conf" \
    -v "$WORK_DIR/docroot:/app/drupal/docroot:ro" "$NGINX_IMAGE" >/dev/null
  # php-fpm shares nginx's network namespace, as in the Lagoon pod, where the
  # config reaches it on 127.0.0.1:9000.
  docker run -d --name "$RUN_ID-php" --network "container:$RUN_ID-nginx" \
    -v "$WORK_DIR/docroot:/app/drupal/docroot:ro" "$PHP_IMAGE" >/dev/null
  BASE_URL="http://$(docker port "$RUN_ID-nginx" 8080/tcp | head -1)"
  local waited=0
  until curl -fsS -o /dev/null -H "Host: $PUBLIC_HOST" "$BASE_URL/" 2>/dev/null &&
    curl -fsS -o /dev/null -H "Host: $PUBLIC_HOST" "$BASE_URL/user/login" 2>/dev/null; do
    waited=$((waited + 1))
    if ((waited > START_TIMEOUT_SECONDS)); then
      echo "nginx did not answer within ${START_TIMEOUT_SECONDS}s" >&2
      docker logs "$RUN_ID-nginx" >&2 || true
      exit 1
    fi
    sleep 1
  done
}

cleanup_containers() {
  docker rm -f "$RUN_ID-nginx" "$RUN_ID-php" "$RUN_ID-frontend" >/dev/null 2>&1 || true
}

# Prints the response headers of one request, lower-cased names, sorted.
headers_of() {
  local host="$1" path="$2"
  curl -sS -o /dev/null -D - -H "Host: $host" "$BASE_URL$path" |
    tr -d '\r' | sed '1s/^[^ ]* \([0-9]*\).*/status: \1/;/^$/d' |
    awk -F': ' '{ name = tolower($1); sub(/^[^:]*: /, ""); print name ": " $0 }' |
    grep -Ev '^(date|x-lagoon|content-length|connection|etag|last-modified|expires|server|x-powered-by|transfer-encoding|accept-ranges|vary|content-encoding): ' |
    sort
}

header_value() {
  grep -i "^$2: " <<<"$1" | sed "s/^[^:]*: //" | paste -sd'|' -
}

expect() {
  local label="$1" actual="$2" expected="$3"
  if [[ "$actual" != "$expected" ]]; then
    echo "  FAIL $label: expected '$expected', got '$actual'"
    FAILURES=$((FAILURES + 1))
  fi
}

# check <environment type> <host> <path> <expected X-Robots-Tag> <expected CSP>
check() {
  local environment_type="$1" host="$2" path="$3" robots="$4" csp="$5"
  local headers
  headers="$(headers_of "$host" "$path")"
  echo "--- $environment_type | $host$path"
  sed 's/^/    /' <<<"$headers"
  if [[ "$REPORT_ONLY" == true ]]; then
    return
  fi
  expect "x-robots-tag" "$(header_value "$headers" x-robots-tag)" "$robots"
  expect "content-security-policy" "$(header_value "$headers" content-security-policy)" "$csp"
  expect "strict-transport-security" "$(header_value "$headers" strict-transport-security)" "max-age=31536000"
  expect "x-content-type-options" "$(header_value "$headers" x-content-type-options)" "nosniff"
  expect "referrer-policy" "$(header_value "$headers" referrer-policy)" "strict-origin-when-cross-origin"
  expect "permissions-policy" "$(header_value "$headers" permissions-policy)" "camera=(), microphone=(), geolocation=()"
}

DEFAULT_CSP="frame-ancestors 'self'"
# 200, 307 (/user/register) and 403 (/admin) answers, with and without a
# language prefix.
ADMIN_PATHS=(
  /user/login /user/password /user/register /user/1 /user/login?destination=/admin
  /admin /admin/content /devel/php /batch /masquerade/1 /unmasquerade
  /media-library /entity-browser/modal /update.php /cron/abc /run-cron
  /node/add /node/add/page /node/preview/abc /taxonomy/term/add
  /node/5/edit /node/5/delete /node/5/revisions /node/5/translations /node/5/latest
  /taxonomy/term/5/edit
  /de/user/login /fr/admin /en/node/add/page /it/node/5/edit
)
# Public content, including paths that only start like an admin path.
PUBLIC_PATHS=(
  / /program /news /user-guide /users /administration /admin-team /batch-of-news
  /cronjobs /node/123 /taxonomy/term/5 /de/news /de/user-guide /media/7
  /core/misc/drupal.js /sites/default/files/photo.png /sitemap.xml /graphql
)
SVG_PATHS=(/sites/default/files/icon.svg /media/7/icon)

run_environment() {
  local environment_type="$1" public_robots="$2" admin_robots="$3"
  start_stack "$environment_type"
  for path in "${ADMIN_PATHS[@]}"; do
    check "$environment_type" "$PUBLIC_HOST" "$path" "$admin_robots" "$DEFAULT_CSP"
  done
  for path in "${PUBLIC_PATHS[@]}"; do
    check "$environment_type" "$PUBLIC_HOST" "$path" "$public_robots" "$DEFAULT_CSP"
  done
  for path in "${SVG_PATHS[@]}"; do
    check "$environment_type" "$PUBLIC_HOST" "$path" "$public_robots" "$SVG_SANDBOX_CSP"
  done
  # Lagoon's autogenerated route is never for search engines.
  check "$environment_type" "$AUTOGENERATED_HOST" "/program" "$NOINDEX" "$DEFAULT_CSP"
}

# Production: only the admin paths are kept out of search engines.
run_environment production "" "$NOINDEX"
# Development: everything is; admin paths carry the header from both rules.
run_environment development "$NOINDEX" "$NOINDEX|$NOINDEX"

if [[ "$REPORT_ONLY" == true ]]; then
  exit 0
fi
if ((FAILURES > 0)); then
  echo "$FAILURES header check(s) failed."
  exit 1
fi
echo "All nginx header checks passed."
