memory_limit = 512M
max_execution_time = 600
xdebug.max_nesting_level = 256
xdebug.show_exception_trace = 0
xdebug.collect_params = 0
xdebug.client_host = ${LANDO_HOST_IP}
xdebug.client_port = 9003
xdebug.log = /tmp/xdebug.log
xdebug.start_with_request = yes
# Very important, else the IP is overridden.
xdebug.discover_client_host = 0
error_log = /tmp/php_error.log
xdebug.output_dir = "/app"
session.cookie_samesite = Lax
